# Generated by Django 3.1.2 on 2022-02-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='BL',
            new_name='bl',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='BU',
            new_name='bu',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='JOBID',
            new_name='jobid',
        ),
    ]
