# Generated by Django 3.1.2 on 2022-02-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20220218_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='endDate',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='isContract',
            new_name='iscontract',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='startDate',
            new_name='startdate',
        ),
    ]
