# Generated by Django 4.0.2 on 2022-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOBID', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('well', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(default='Iraq', max_length=255)),
                ('BU', models.CharField(blank=True, default='KIU', max_length=3, null=True)),
                ('BL', models.CharField(blank=True, default='SWT', max_length=3, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('isContract', models.BooleanField(blank=True, default=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
