# Generated by Django 3.1.2 on 2022-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='BL',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
