# Generated by Django 3.1.2 on 2022-02-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_bl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='BL',
            new_name='bl',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='BU',
            new_name='bu',
        ),
    ]
